name:                duvet
version:             1.0.0.0
github:              "dixonary/duvet"
license:             BSD3
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           "2019 Alex Dixon"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/dixonary/duvet#readme>

default-extensions:
- ApplicativeDo
- GeneralizedNewtypeDeriving
- TypeSynonymInstances
- FlexibleInstances
- OverloadedStrings
- OverloadedLists
- DuplicateRecordFields
- RecordWildCards
- LambdaCase
- TupleSections

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- vector
- containers
- megaparsec
- pretty-simple
- vass
- text
- timeit
- cassava
- bytestring
- filepath
- silently

library:
  source-dirs: src

executables:
  duvet:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - duvet


# tests:
#   duvet-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - duvet
